"""secrets table

Revision ID: 1c923be08e9a
Revises: 
Create Date: 2021-06-02 21:51:26.103594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c923be08e9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('data', sa.String(length=32768), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_email', sa.String(length=128), nullable=True),
    sa.Column('max_views', sa.Integer(), nullable=False),
    sa.Column('delete_after', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secret')
    # ### end Alembic commands ###
